name: Publish to Comfy Registry

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - pyproject.toml

permissions:
  contents: read

jobs:
  publish:
    name: Publish custom node
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Publish to Comfy Registry
        uses: Comfy-Org/publish-node-action@d2366e7abb6ab16f3bb03e3520ae25c8cf749bc9
        with:
          skip_checkout: "true"
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
